spring.application.name=manufacturing-system

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmatrust_db
spring.datasource.username=postgres
spring.datasource.password=5593

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

